-- modul_bumil: schema identitas & kunjungan ibu hamil (data eksisting aman,
-- CREATE TABLE IF NOT EXISTS agar replikasi fresh berfungsi)

-- 1. tabel identitas
create table if not exists public.bumil_identitas (
  id bigint generated by default as identity primary key,
  nama text,
  nik text,
  tanggal_lahir date,
  umur text,
  nama_suami text,
  nomor_kk text,
  alamat text,
  dusun text,
  hamil_anak_ke text,
  jarak_dengan_anak_sebelumnya text,
  tanggal_bersalin date,
  tempat_bersalin text,
  cara_persalin text,
  anak_ke text,
  kategori text,
  created_at timestamptz not null default now()
);

-- 1b. tabel kunjungan
create table if not exists public.bumil_kunjungan (
  id bigint generated by default as identity primary key,
  bumil_id bigint references public.bumil_identitas (id) on delete set null,
  nama text,
  tanggal_kunjungan date,
  usia_kehamilan_minggu numeric,
  berat_badan numeric,
  bb_sesuai_kurva_kia text,
  lingkaran_lengan_atas numeric,
  lila_hijau_merah text,
  tekanan_darah text,
  td_sesuai_kurva_kia text,
  batuk_terus_menerus text,
  demam_lebih_dua_minggu text,
  bb_tidak_naik_dua_bulan text,
  kontak_tbc text,
  dapat_tablet_ttd text,
  konsumsi_ttd text,
  mt_kek_diberikan text,
  konsumsi_mt_kek text,
  kelas_bumil text,
  dapat_edukasi text,
  dirujuk text,
  created_at timestamptz not null default now()
);

-- 2. identity idempotent utk tabel yang sudah ada sebelum migrasi
do $$
begin
  if exists (select 1 from pg_attribute where attrelid = 'public.bumil_identitas'::regclass and attname = 'id' and attidentity = '') then
    alter table public.bumil_identitas alter column id add generated by default as identity;
  end if;
  if exists (select 1 from pg_attribute where attrelid = 'public.bumil_kunjungan'::regclass and attname = 'id' and attidentity = '') then
    alter table public.bumil_kunjungan alter column id add generated by default as identity;
  end if;
end $$;

-- 2b. mulai sequence dari id terbesar yang sudah ada (hindari konflik)
select setval(
  pg_get_serial_sequence('public.bumil_identitas', 'id'),
  coalesce((select max(id) from public.bumil_identitas), 1)
);
select setval(
  pg_get_serial_sequence('public.bumil_kunjungan', 'id'),
  coalesce((select max(id) from public.bumil_kunjungan), 1)
);

-- 3. kolom FK di bumil_kunjungan (idempotent utk tabel legacy)
alter table public.bumil_kunjungan
  add column if not exists bumil_id bigint references public.bumil_identitas (id) on delete set null;

-- 4. backfill relasi dari nama (trim + case-insensitive)
update public.bumil_kunjungan k
set bumil_id = b.id
from public.bumil_identitas b
where k.bumil_id is null
  and lower(trim(k.nama)) = lower(trim(b.nama));

-- 5. index query per bumil
create index if not exists idx_bumil_kunjungan_bumil_id
  on public.bumil_kunjungan (bumil_id);

-- 6. RLS ketat (mirip balita): kader read, admin write, service_role all
alter table public.bumil_identitas enable row level security;
alter table public.bumil_kunjungan enable row level security;

drop policy if exists "anon_select_bumil_identitas" on public.bumil_identitas;
drop policy if exists "anon_select_bumil_kunjungan" on public.bumil_kunjungan;
drop policy if exists "auth_select_bumil_identitas" on public.bumil_identitas;
drop policy if exists "auth_select_bumil_kunjungan" on public.bumil_kunjungan;
drop policy if exists "service_all_bumil_identitas" on public.bumil_identitas;
drop policy if exists "service_all_bumil_kunjungan" on public.bumil_kunjungan;
drop policy if exists "kader_baca_bumil_identitas" on public.bumil_identitas;
drop policy if exists "kader_baca_bumil_kunjungan" on public.bumil_kunjungan;
drop policy if exists "admin_tambah_bumil_identitas" on public.bumil_identitas;
drop policy if exists "admin_tambah_bumil_kunjungan" on public.bumil_kunjungan;
drop policy if exists "admin_ubah_bumil_identitas" on public.bumil_identitas;
drop policy if exists "admin_ubah_bumil_kunjungan" on public.bumil_kunjungan;
drop policy if exists "admin_hapus_bumil_identitas" on public.bumil_identitas;
drop policy if exists "admin_hapus_bumil_kunjungan" on public.bumil_kunjungan;

create policy "kader_baca_bumil_identitas"
  on public.bumil_identitas for select
  to authenticated
  using (true);

create policy "kader_baca_bumil_kunjungan"
  on public.bumil_kunjungan for select
  to authenticated
  using (true);

create policy "admin_tambah_bumil_identitas"
  on public.bumil_identitas for insert
  to authenticated
  with check (is_admin());

create policy "admin_tambah_bumil_kunjungan"
  on public.bumil_kunjungan for insert
  to authenticated
  with check (is_admin());

create policy "admin_ubah_bumil_identitas"
  on public.bumil_identitas for update
  to authenticated
  using (is_admin());

create policy "admin_ubah_bumil_kunjungan"
  on public.bumil_kunjungan for update
  to authenticated
  using (is_admin());

create policy "admin_hapus_bumil_identitas"
  on public.bumil_identitas for delete
  to authenticated
  using (is_admin());

create policy "admin_hapus_bumil_kunjungan"
  on public.bumil_kunjungan for delete
  to authenticated
  using (is_admin());

create policy "service_all_bumil_identitas"
  on public.bumil_identitas for all
  to service_role
  using (true)
  with check (true);

create policy "service_all_bumil_kunjungan"
  on public.bumil_kunjungan for all
  to service_role
  using (true)
  with check (true);
