-- modul_apras (fase 1): tabel identitas anak pra sekolah usia 5–6 tahun.
-- Kolom identik dengan balita_identitas; kunjungan menyusul setelah diskusi plan.
-- Semua statement idempotent agar replikasi fresh aman.

create table if not exists public.apras_identitas (
  id bigint generated by default as identity primary key,
  nama text,
  nik text,
  jenis_kelamin text,
  tanggal_lahir date,
  tempat_lahir text,
  anak_ke text,
  nama_orang_tua text,
  nik_orang_tua text,
  nomor_kk text,
  dusun text,
  alamat text,
  bb_lahir numeric,
  pb_lahir numeric,
  posyandu text,
  created_at timestamptz not null default now(),
  dibuat_oleh uuid,
  sasaran text
);

-- identity idempotent utk tabel yang mungkin sudah ada sebelum migrasi ini
do $$
begin
  if exists (select 1 from pg_attribute where attrelid = 'public.apras_identitas'::regclass and attname = 'id' and attidentity = '') then
    alter table public.apras_identitas alter column id add generated by default as identity;
  end if;
end $$;

-- RLS ketat: anonim ditolak, kader terautentikasi baca/tulis
alter table public.apras_identitas enable row level security;

drop policy if exists "kader_baca_apras" on public.apras_identitas;
create policy "kader_baca_apras" on public.apras_identitas
  for select to authenticated using (true);

drop policy if exists "kader_tambah_apras" on public.apras_identitas;
create policy "kader_tambah_apras" on public.apras_identitas
  for insert to authenticated with check (dibuat_oleh = auth.uid());

drop policy if exists "kader_ubah_apras" on public.apras_identitas;
create policy "kader_ubah_apras" on public.apras_identitas
  for update to authenticated using (true);

drop policy if exists "kader_hapus_apras" on public.apras_identitas;
create policy "kader_hapus_apras" on public.apras_identitas
  for delete to authenticated using (true);
