-- relasi_balita: relasi kunjungan → balita (additif, data eksisting aman)

-- 1. balita_identitas.id bisa di-generate saat INSERT (id lama tetap)
alter table public.balita_identitas
  alter column id add generated by default as identity;

-- 1b. mulai sequence dari id terbesar yang sudah ada (hindari konflik)
select setval(
  pg_get_serial_sequence('public.balita_identitas', 'id'),
  coalesce((select max(id) from public.balita_identitas), 1)
);

-- 2. kolom FK di balita_kunjungan
alter table public.balita_kunjungan
  add column if not exists balita_id bigint references public.balita_identitas (id) on delete set null;

-- 3. backfill relasi dari nama_anak (trim + case-insensitive)
update public.balita_kunjungan k
set balita_id = b.id
from public.balita_identitas b
where k.balita_id is null
  and lower(trim(k.nama_anak)) = lower(trim(b.nama));

-- 4. index query per balita
create index if not exists idx_balita_kunjungan_balita_id
  on public.balita_kunjungan (balita_id);
