-- modul_apras (fase 2): tabel kunjungan anak pra sekolah usia 61–72 bulan (5–6 tahun).
-- Disesuaikan usia (beda dari balita):
-- - TANPA vitamin A (hanya sampai 60 bln), TANPA asi_eksklusif & mp_asi (bukan bayi/balita)
-- - Pengukuran inti: umur_bulan, berat_badan, tinggi_badan, lingkar_lengan (LiLA), lingkar_kepala (LiKA)
-- - Kolom status/z-score TIDAK dibuat: referensi WHO LMS hanya sampai 60 bulan
--   (wfa/lhfa/hcfa/acfa max kunci=60; wfl per panjang badan tetap tersedia utk BB/TB bila nanti perlu)
-- Idempotent agar replikasi fresh aman.

create table if not exists public.apras_kunjungan (
  id bigint generated by default as identity primary key,
  apras_id bigint references public.apras_identitas (id) on delete set null,
  nama_anak text,
  umur_bulan integer,
  tanggal_kunjungan date,
  berat_badan numeric,
  tinggi_badan numeric,
  lingkar_lengan numeric,
  lingkar_kepala numeric,
  gejala_tbc text,
  imunisasi text,
  obat_cacing text,
  mt_pangan_lokal text,
  edukasi text,
  dirujuk text,
  catatan text,
  created_at timestamptz not null default now(),
  dibuat_oleh uuid
);

-- identity idempotent
do $$
begin
  if exists (select 1 from pg_attribute where attrelid = 'public.apras_kunjungan'::regclass and attname = 'id' and attidentity = '') then
    alter table public.apras_kunjungan alter column id add generated by default as identity;
  end if;
end $$;

-- RLS ketat mengikuti pola balita
alter table public.apras_kunjungan enable row level security;

drop policy if exists "kader_baca_apras_kunjungan" on public.apras_kunjungan;
create policy "kader_baca_apras_kunjungan" on public.apras_kunjungan
  for select to authenticated using (true);

drop policy if exists "kader_tambah_apras_kunjungan" on public.apras_kunjungan;
create policy "kader_tambah_apras_kunjungan" on public.apras_kunjungan
  for insert to authenticated with check (dibuat_oleh = auth.uid());

drop policy if exists "kader_ubah_apras_kunjungan" on public.apras_kunjungan;
create policy "kader_ubah_apras_kunjungan" on public.apras_kunjungan
  for update to authenticated using (true);

drop policy if exists "kader_hapus_apras_kunjungan" on public.apras_kunjungan;
create policy "kader_hapus_apras_kunjungan" on public.apras_kunjungan
  for delete to authenticated using (true);
