-- modul_remaja (fase 2): tabel kunjungan remaja (7–18 tahun).
--
-- Mengikuti pola apras_kunjungan / balita_kunjungan (struktur DB "tetap mirip"
-- dengan modul lain). Penilaian gizi remaja memakai indeks massa tubuh (IMT)
-- per umur; untuk saat ini nilai imt & status_gizi diisi MANUAL oleh kader
-- (hitung otomatis & tabel referensi BMI-for-age WHO 2007 menyusul batch
-- berikutnya). Column status_gizi disediakan agar migrasi otomatis mudah
-- diaktifkan nanti.
--
-- Kebijakan akses (v2.39.4): tulis admin-only; kader (non-admin) read-only.
-- Semua statement idempotent agar replikasi fresh aman.

create table if not exists public.remaja_kunjungan (
  id bigint generated by default as identity primary key,
  remaja_id bigint references public.remaja_identitas (id) on delete set null,
  nama_remaja text,
  umur_tahun numeric,
  tanggal_kunjungan date,
  -- Hasil Penimbangan/Pengukuran/Pemeriksaan
  berat_badan numeric,
  tinggi_badan numeric,
  imt numeric,
  status_gizi text,
  -- Pemeriksaan remaja (umur >= 15 tahun)
  lingkar_perut numeric,
  td_sistole integer,
  td_diastole integer,
  td_kategori text,
  gula_darah numeric,
  gula_kategori text,
  hb numeric,
  anemia text,
  -- Skrining gejala TBC
  batuk_terus_menerus text,
  demam_lebih_dua_minggu text,
  bb_tidak_naik_dua_bulan text,
  kontak_erat_tbc text,
  -- Layanan
  edukasi text,
  rujuk text,
  catatan text,
  created_at timestamptz not null default now(),
  dibuat_oleh uuid
);

-- identity idempotent utk tabel yang mungkin sudah ada sebelum migrasi ini
do $$
begin
  if exists (select 1 from pg_attribute where attrelid = 'public.remaja_kunjungan'::regclass and attname = 'id' and attidentity = '') then
    alter table public.remaja_kunjungan alter column id add generated by default as identity;
  end if;
end $$;

-- RLS ketat: kader (authenticated) baca saja; tulis hanya admin.
alter table public.remaja_kunjungan enable row level security;

drop policy if exists "kader_baca_remaja_kunjungan" on public.remaja_kunjungan;
create policy "kader_baca_remaja_kunjungan" on public.remaja_kunjungan
  for select to authenticated using (true);

drop policy if exists "admin_tambah_remaja_kunjungan" on public.remaja_kunjungan;
create policy "admin_tambah_remaja_kunjungan" on public.remaja_kunjungan
  for insert to authenticated
  with check (public.is_admin() and dibuat_oleh = auth.uid());

drop policy if exists "admin_ubah_remaja_kunjungan" on public.remaja_kunjungan;
create policy "admin_ubah_remaja_kunjungan" on public.remaja_kunjungan
  for update to authenticated using (public.is_admin());

drop policy if exists "admin_hapus_remaja_kunjungan" on public.remaja_kunjungan;
create policy "admin_hapus_remaja_kunjungan" on public.remaja_kunjungan
  for delete to authenticated using (public.is_admin());

-- trigger auto-fill dibuat_oleh dari sesi login
drop trigger if exists trg_remaja_kunjungan_dibuat_oleh on public.remaja_kunjungan;
create trigger trg_remaja_kunjungan_dibuat_oleh
  before insert on public.remaja_kunjungan
  for each row execute function public.set_dibuat_oleh();
