-- modul_remaja (fase 1): tabel identitas anak usia sekolah / remaja 7–18 tahun.
-- Kolom mengikuti balita_identitas/apras_identitas TANPA bb_lahir/pb_lahir/sasaran
-- (tidak relevan utk kelompok umur ini) + kolom tambahan nama_sekolah.
-- Kunjungan & standar antropometri remaja menyusul batch berikutnya.
-- Semua statement idempotent agar replikasi fresh aman.

create table if not exists public.remaja_identitas (
  id bigint generated by default as identity primary key,
  nama text,
  nik text,
  jenis_kelamin text,
  tanggal_lahir date,
  tempat_lahir text,
  anak_ke text,
  nama_orang_tua text,
  nik_orang_tua text,
  nomor_kk text,
  dusun text,
  alamat text,
  posyandu text,
  nama_sekolah text,
  created_at timestamptz not null default now(),
  dibuat_oleh uuid
);

-- identity idempotent utk tabel yang mungkin sudah ada sebelum migrasi ini
do $$
begin
  if exists (select 1 from pg_attribute where attrelid = 'public.remaja_identitas'::regclass and attname = 'id' and attidentity = '') then
    alter table public.remaja_identitas alter column id add generated by default as identity;
  end if;
end $$;

-- RLS ketat: anonim ditolak, kader terautentikasi baca saja; tulis hanya admin.
alter table public.remaja_identitas enable row level security;

drop policy if exists "kader_baca_remaja" on public.remaja_identitas;
create policy "kader_baca_remaja" on public.remaja_identitas
  for select to authenticated using (true);

drop policy if exists "admin_tambah_remaja" on public.remaja_identitas;
create policy "admin_tambah_remaja" on public.remaja_identitas
  for insert to authenticated
  with check (public.is_admin() and dibuat_oleh = auth.uid());

drop policy if exists "admin_ubah_remaja" on public.remaja_identitas;
create policy "admin_ubah_remaja" on public.remaja_identitas
  for update to authenticated using (public.is_admin());

drop policy if exists "admin_hapus_remaja" on public.remaja_identitas;
create policy "admin_hapus_remaja" on public.remaja_identitas
  for delete to authenticated using (public.is_admin());

-- service_role (bypass RLS) otomatis punya akses penuh, tidak perlu policy.
-- Trigger auto-fill dibuat_oleh dari sesi login (fungsi shared set_dibuat_oleh).
drop trigger if exists trg_remaja_identitas_dibuat_oleh on public.remaja_identitas;

create trigger trg_remaja_identitas_dibuat_oleh
  before insert on public.remaja_identitas
  for each row execute function public.set_dibuat_oleh();
